version: '3'
services:
  app:
    build: .
    command: npm run start
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports: 
      - "8000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres@db:5432/postgres
      LOCAL: true
  db:
    image: postgres:latest
    volumes:
     - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
     - ./users.sql:/docker-entrypoint-initdb.d/2-users.sql
     - ./main_topics.sql:/docker-entrypoint-initdb.d/3-main_topics.sql
     - ./subtopics.sql:/docker-entrypoint-initdb.d/4-subtopics.sql
     - ./ideas.sql:/docker-entrypoint-initdb.d/5-ideas.sql
     - ./comments.sql:/docker-entrypoint-initdb.d/6-comments.sql
     - ./admin.sql:/docker-entrypoint-initdb.d/6-admin.sql
    ports:
      - "8001:5432"