version: '3'
services:
  app:
    build: .
    command: npm run start
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports: 
      - "8000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres@db:5432/postgres
  db:
    image: postgres:latest
    volumes:
     - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    #environment:
      #POSTGRES_DB: psp
    ports:
      - "8001:5432"