version: '3'
services:
  app:
    build: .
    command: npm run start
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports: 
      - "8000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres@db:5432/postgres
      FIREBASE_PRIVATE_KEY:
      FIREBASE_CLIENT_EMAIL:
      FIREBASE_PRIVATE_KEY_ID:
      FIREBASE_PROJECT_ID:
  db:
    image: postgres:latest
    volumes:
     - ./db/init.sql:/docker-entrypoint-initdb.d/1-init.sql
     - ./db/users.sql:/docker-entrypoint-initdb.d/2-users.sql
     - ./db/main_topics.sql:/docker-entrypoint-initdb.d/3-main_topics.sql
     - ./db/subtopics.sql:/docker-entrypoint-initdb.d/4-subtopics.sql
     - ./db/ideas.sql:/docker-entrypoint-initdb.d/5-ideas.sql
     - ./db/comments.sql:/docker-entrypoint-initdb.d/6-comments.sql
     - ./db/admin.sql:/docker-entrypoint-initdb.d/6-admin.sql
    ports:
      - "8001:5432"